# -*- coding: utf-8 -*-
"""assign1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZQgRdBNxBmNWgEbUHRB4rZ8teSgxjX5

ANANYA V R   
USN:4RA21EC007
DATE:11/09/2024

1. Understanding Variables
a) Define a variable in Python. Provide an example of how to create a variable that stores your name.

Varaible acts as an address for where the data is stored in memeory
"""

x=10

"""b) What is the difference between a variable and a constant? Can we have constants in Python?

in variables we can change the data but in constants we can't change data it is fixed. no it can't have any constant in varible

2. Working with Different Data Types
a) Create variables of the following types in Python:

1.
Integer
2.
Float
3.
String
4.
Boolean
"""

num1=10
type(num1)

num2=1.23
type(num2)

num3="30"
type(num3)

a=True
type(a)

"""b) Write a Python script to display the type of each variable you created."""

a = 10
b = 22.10
c = "Hello PYTHON"
d = True
e = [1, 2, 3]
f = {"name": "J", "age": 10}
g = (1, 2, 3)

print(f"a = {a}: {type(a)}")
print(f"b = {b}: {type(b)}")
print(f"c = {c}: {type(c)}")
print(f"d = {d}: {type(d)}")
print(f"e = {e}: {type(e)}")
print(f"f = {f}: {type(f)}")
print(f"g = {g}: {type(g)}")

"""3.Arithmetic Operators

1 addition:arithmetic operator where sum of input takeplace
"""

a=20
b=5
sum=a+b
print(sum)

"""2 subtraction:arithmetic operator where diffrence of input takeplace"""

diff=a-b
print(diff)

"""3 multiplication:arithmetic operator where product of input takeplace"""

mult=a*b
print(mult)

"""4 division:arithmetic operator where divides first opeate by second"""

div=a/b
print(div)

"""5 floor division:arithmetic operator where divides first opeate by second"""

val1=5
val2=4
result=val1//val2
print(result)

"""6 modulus:arithmetic operator where returns the reminde when first opeate divides by second"""

val1=5
val2=4
result=val1%val2
print(result)

"""7exponent:arithmetic operator where returns first raised to power second"""

val1=3
val2=2
result=val1**val2
print(result)

"""b) Write a Python script to calculate the area of a rectangle using variables `length` and `width` with values 5 and 10, respectively. Use the multiplication operator."""

length=5
width=10
area=length*width
print(area)

"""4.a) Explain the following comparison operators with examples:

1.
Equal to:True if both operands are equal

a == b
"""

a=10
b=10
a==b

"""2Not equal to :Inequality Operators !=

"""

a=10
b=5
a!=b

"""3.Greater than: True if the left operand is greater than the right"""

a=10
b=5
a>b

"""4.Less than: True if the left operand is less than the right

"""

a<b

"""5.
Greater than or equal to:True if left operand is greater than or equal to the right	a >= b

6
Less than or Equal to:True if left operand is less than or equal to the right	a <= b




"""

a=9
b=5
c=10
print(a<=b)
print(a<=c)
print(a>=b)

"""4b) Using logical operators (`and`, `or`, `not`), write a Python script that checks if a number is positive and even."""

num = 4
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")
if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

"""5.a) What is type casting? Explain the difference between implicit and explicit type casting with examples.

type casting:the process of converting one data type into another form

In implicit type casting, the programming language automatically converts data from one type to another if needed. For example, if you have an integer variable and you try to assign it to a float variable, the programming language will automatically convert the integer to a float without you having to do anything.

Explicit type casting, also known as type conversion, occurs when the programmer explicitly converts a value from one data type to another. Unlike implicit type casting, explicit type casting requires the programmer to specify the desired data type conversion.

5b) Write a Python script that:

1.
Converts a float to an integer.
"""

num = 5.234
int_num = int(num)
print(f"Float to int: {num} -> {int_num}")

"""2.Converts an integer to a string."""

string = str(int_num)
print(f"Int to str: {int_num} -> {string}")

"""3.
Converts a string to a float.
"""

float_num = float(string)
print("Str to float: {string} -> {float_num_}")

"""6.  Mini Calculator"""

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
sum = num1 + num2
print(f"Sum: {sum}")
difference = num1 - num2
print(f"Difference: {difference}")
product = num1 * num2
print(f"Product: {product}")
if num2 != 0:
    quotient = num1 / num2
    print(f"Quotient: {quotient}")
else:
    print("Error: Division by zero is not allowed.")
sum_str = str(sum)
print(f"Sum as string: {sum_str}")
print(f"Type of sum_str: {type(sum_str)}")

